title: DanAukes.com
author: Dan Aukes
email: danaukes-at-gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Dan Aukes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danaukes.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: danaukes
github_username:  danb0b

# Build settings
markdown: kramdown

plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


menu:
#  - name: EGR598
#    link: egr598
    - name: code
      link: code
    - name: recipes
      link: recipes
    - name: bookmarks
      link: my_bookmarks
    - name: notebook
      link: my_notebook
    - name: calendar
      link: calendar
    

collections:
  recipes:
    output: true
  code:
    output: true
  notebook:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "bookmarks"
    values:
      type: "bookmarks"
  - scope:
      type: "recipes"
    values:
      layout: recipe
  - scope:
      type: "code"
    values:
      layout: page

plugins: 
  - jekyll-include-cache
